=== isarandi/medical_coding_thesis/classifier_architectures/architecture.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!ELEMENT architecture (classifier)*>
<!ELEMENT classifier ((type, param*, inputtransform*, outputtransform*)*| (inputtransform*, outputtransform*))>
<!ATTLIST classifier
    ref CDATA #IMPLIED
    file CDATA #IMPLIED
    id CDATA #IMPLIED
  >

<!ELEMENT type (#PCDATA)>
<!ELEMENT inputtransform (#PCDATA)>
<!ELEMENT outputtransform (#PCDATA)>
<!ELEMENT param (#PCDATA|converter|classifier|learningmonitor)*>
<!ATTLIST param
    name CDATA #REQUIRED
  >
<!ELEMENT converter (param|type)*>
<!ELEMENT learningmonitor (param|type)*>

=== isarandi/medical_coding_thesis/classifier_architectures/svm_idf_mix.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE architecture SYSTEM "architecture.dtd">

<architecture>

    <classifier id="idf">
        <type>VectorSpace</type>
        <inputtransform>idf</inputtransform>
    </classifier>    
  
    <classifier id="svm">
        <type>LibLinear</type>
        <param name="c">10</param>
        <outputtransform>counter</outputtransform>
    </classifier>
   
       
    <classifier id="team">
        <type>ConstantWeightTeam</type>
        <param name="c1">
            <classifier ref="svm" />
        </param>
        <param name="c2">
            <classifier ref="idf" />
        </param>
        <param name="ratio">0.4</param>
    </classifier>
    
    <classifier id="main" ref="team">
        <inputtransform>bagofwords</inputtransform>
    </classifier>
</architecture>

=== isarandi/medical_coding_thesis/classifier_architectures/perceptron_idf_mix.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE architecture SYSTEM "architecture.dtd">

<architecture>

    <classifier id="idf">
        <type>VectorSpace</type>
        <inputtransform>idf</inputtransform>
    </classifier>    
  
    <classifier id="mlp">
        <type>MLP</type>
        <param name="learnrate">0.1</param>
        <param name="maxepochs">3000</param>
        <param name="splitratio">0.9</param>
        <param name="learningmonitor">
            <learningmonitor>
                <type>DecreaseRatio</type>
                <param name="ratio">0.2</param>
                <param name="windowsize">5</param>
            </learningmonitor>
        </param>
        <param name="errorcalculator">LogLikelihood</param>
        <outputtransform>counter</outputtransform>
    </classifier>
   
    
    <classifier id="team">
        <type>ConstantWeightTeam</type>
        <param name="c1">
            <classifier ref="mlp">

            </classifier>
        </param>
        <param name="c2">
            <classifier ref="idf">

            </classifier>
        </param>
        <param name="ratio">0.4</param>
    </classifier>
    
    <classifier id="main" ref="team">
        <inputtransform>bagofwords</inputtransform>
    </classifier>
</architecture>

=== isarandi/medical_coding_thesis/classifier_architectures/svm_moe_perceptron_moe_mix.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE architecture SYSTEM "architecture.dtd">

<architecture>

  
    <classifier id="svm">
        <type>LibLinear</type>
        <param name="c">10</param>
    </classifier>
    
        <classifier id="mlp">
        <type>MLP</type>
        <param name="learnrate">0.1</param>
        <param name="maxepochs">3000</param>
        <param name="splitratio">0.9</param>
        <param name="learningmonitor">
            <learningmonitor>
                <type>DecreaseRatio</type>
                <param name="ratio">0.2</param>
                <param name="windowsize">5</param>
            </learningmonitor>
        </param>
        <param name="errorcalculator">LogLikelihood</param>
    </classifier>

   
    <classifier id="moemlp">
        <type>Hierarchic</type>
        <param name="root">
            <classifier ref="mlp" />
        </param>
        <param name="child">
            <classifier ref="mlp">
                <inputtransform>compress</inputtransform>
                <outputtransform>counter</outputtransform>
            </classifier>
        </param>
        <param name="childselector">
            <converter>
                <type>Interval</type>
                <param name="file">code_chapters.txt</param>
            </converter>
        </param>
    </classifier>

   
    <classifier id="moesvm">
        <type>Hierarchic</type>
        <param name="root">
            <classifier ref="svm" />
        </param>
        <param name="child">
            <classifier ref="svm">
                <inputtransform>compress</inputtransform>
                <outputtransform>counter</outputtransform>
            </classifier>
        </param>
        <param name="childselector">
            <converter>
                <type>Interval</type>
                <param name="file">code_chapters.txt</param>
            </converter>
        </param>
    </classifier>

    
    <classifier id="team">
        <type>ConstantWeightTeam</type>
        <param name="c1">
            <classifier ref="moemlp">

            </classifier>
        </param>
        <param name="c2">
            <classifier ref="moesvm">

            </classifier>
        </param>
        <param name="ratio">0.4</param>
    </classifier>
    
    <classifier id="main" ref="team">
        <inputtransform>bagofwords</inputtransform>
    </classifier>
</architecture>

=== isarandi/medical_coding_thesis/classifier_architectures/perceptron.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE architecture SYSTEM "architecture.dtd">

<architecture>

    <classifier id="mlp">
        <type>MLP</type>
        <param name="learnrate">0.1</param>
        <param name="maxepochs">3000</param>
        <param name="splitratio">0.9</param>
        <param name="learningmonitor">
            <learningmonitor>
                <type>DecreaseRatio</type>
                <param name="ratio">0.2</param>
                <param name="windowsize">5</param>
            </learningmonitor>
        </param>
        <param name="errorcalculator">LogLikelihood</param>
    </classifier>

        
    <classifier id="main" ref="mlp">
        <inputtransform>bagofwords</inputtransform>
        <outputtransform>counter</outputtransform>
    </classifier>
</architecture>

=== isarandi/medical_coding_thesis/classifier_architectures/svm_moe_idf_mix.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE architecture SYSTEM "architecture.dtd">

<architecture>

    <classifier id="idf">
        <type>VectorSpace</type>
        <inputtransform>idf</inputtransform>
    </classifier>    
  
    <classifier id="svm">
        <type>LibLinear</type>
        <param name="c">10</param>
    </classifier>

   
    <classifier id="moe">
        <type>Hierarchic</type>
        <param name="root">
            <classifier ref="svm" />
        </param>
        <param name="child">
            <classifier ref="svm">
                <inputtransform>compress</inputtransform>
                <outputtransform>counter</outputtransform>
            </classifier>
        </param>
        <param name="childselector">
            <converter>
                <type>Interval</type>
                <param name="file">code_chapters.txt</param>
            </converter>
        </param>
    </classifier>

    
    <classifier id="team">
        <type>ConstantWeightTeam</type>
        <param name="c1">
            <classifier ref="moe">

            </classifier>
        </param>
        <param name="c2">
            <classifier ref="idf">

            </classifier>
        </param>
        <param name="ratio">0.4</param>
    </classifier>
    
    <classifier id="main" ref="team">
        <inputtransform>bagofwords</inputtransform>
    </classifier>
</architecture>

=== isarandi/medical_coding_thesis/classifier_architectures/perceptron_moe_idf_mix.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE architecture SYSTEM "architecture.dtd">

<architecture>

    <classifier id="idf">
        <type>VectorSpace</type>
        <inputtransform>idf</inputtransform>
    </classifier>    
  
    <classifier id="mlp">
        <type>MLP</type>
        <param name="learnrate">0.1</param>
        <param name="maxepochs">3000</param>
        <param name="splitratio">0.9</param>
        <param name="learningmonitor">
            <learningmonitor>
                <type>DecreaseRatio</type>
                <param name="ratio">0.2</param>
                <param name="windowsize">5</param>
            </learningmonitor>
        </param>
        <param name="errorcalculator">LogLikelihood</param>
    </classifier>
   
    <classifier id="moe">
        <type>Hierarchic</type>
        <param name="root">
            <classifier ref="mlp" />
        </param>
        <param name="child">
            <classifier ref="mlp">
                <inputtransform>compress</inputtransform>
                <outputtransform>counter</outputtransform>
            </classifier>
        </param>
        <param name="childselector">
            <converter>
                <type>Interval</type>
                <param name="file">code_chapters.txt</param>
            </converter>
        </param>
    </classifier>
    
    <classifier id="team">
        <type>ConstantWeightTeam</type>
        <param name="c1">
            <classifier ref="moe">

            </classifier>
        </param>
        <param name="c2">
            <classifier ref="idf">

            </classifier>
        </param>
        <param name="ratio">0.4</param>
    </classifier>
    
    <classifier id="main" ref="team">
        <inputtransform>bagofwords</inputtransform>
    </classifier>
</architecture>

=== isarandi/medical_coding_thesis/classifier_architectures/svm_moe.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE architecture SYSTEM "architecture.dtd">

<architecture>
    
  
    <classifier id="svm">
        <type>LibLinear</type>
        <param name="c">10</param>
    </classifier>

   
    <classifier id="hier">
        <type>Hierarchic</type>
        <param name="root">
            <classifier ref="svm" />
        </param>
        <param name="child">
            <classifier ref="svm">
                <inputtransform>compress</inputtransform>
                <outputtransform>counter</outputtransform>
            </classifier>
        </param>
        <param name="childselector">
            <converter>
                <type>Interval</type>
                <param name="file">code_chapters.txt</param>
            </converter>
        </param>
    </classifier>
    
    <classifier id="main" ref="hier">
        <inputtransform>bagofwords</inputtransform>
    </classifier>
</architecture>
